### ISSUE TITLE
ModuleNotFoundError: No module named 'models.trans_ablation' error

### ISSUE THREAD

**Issue by Jihyun0510** [PengleiGao/UTransformer#1]
Hello
Thanks for your great work

when runing train_transformer4.py, I counterd the following error

`Traceback (most recent call last):
  File "train_transformer4.py", line 11, in <module>
    from models.build4 import build_model, ImagePool
  File "/home/jsh/jhkim/UTransformer/models/build4.py", line 2, in <module>
    from .trans_ablation import Ablation`

in build4.py in models directory, in line 2 Abaltion is imported from trans_abaltion.

`from .trans_ablation import Ablation`

However, I do not find any python file named "trans_ablation" in models folder.
Where can I get the full code??

Thank you

**Comment by PengleiGao** [comment]
Hi, you can comment the code 'from .trans_ablation import Ablation' in line2 in build4.py

**Comment by Jihyun0510** [comment]
Thanks for your comment

However I get the following error when running trans_transformer4.py:
`ModuleNotFoundError: No module named 'models.trans_ablation'`

How can I solve this error?

**Comment by PengleiGao** [comment]
Hi, I didn't see any code of "trans_ablation" in file tran_transformer4.py.
Have you comment the code 'from .trans_ablation import Ablation' in line2 in build4.py? That means you have to delete this line.

**Comment by Jihyun0510** [comment]
Thanks! I did not know "comment" meant "delete"
deleting the line solved the problem

I also encountered the following error:

```
Traceback (most recent call last):
  File "train_transformer4.py", line 13, in <module>
    from utils.loss import IDMRFLoss
  File "/home/jsh/jhkim/UTransformer/utils/loss.py", line 4, in <module>
    from models.layer import VGG19FeatLayer
ModuleNotFoundError: No module named 'models.layer'
```

Deleteing "from models.layer impot VGG19FeatLayer" from loss.py raised the following error:

```
Traceback (most recent call last):
  File "train_transformer4.py", line 13, in <module>
    from utils.loss import IDMRFLoss
  File "/home/jsh/jhkim/UTransformer/utils/loss.py", line 21, in <module>
    class IDMRFLoss(nn.Module):
  File "/home/jsh/jhkim/UTransformer/utils/loss.py", line 22, in IDMRFLoss
    def __init__(self, featlayer=VGG19FeatLayer, device=0, shallow_feats=False):
NameError: name 'VGG19FeatLayer' is not defined
```
Maybe there are more codes to be uploaded???

**Comment by PengleiGao** [comment]
Hi, do not delete "from models.layer import VGG19FeatLayer" in file loss.py.
I have updated the necessary files. You could re-download the code.

**Comment by Jihyun0510** [comment]
Thanks, that works!
