### ISSUE TITLE
codes for horizontal extrapolation

### ISSUE THREAD

**Issue by Jihyun0510** [PengleiGao/UTransformer#2]
Hello

Reading your codes, they appear to be for generalised outpainting.
Do u have any plan to release codes for horizontal one??
Moreover I would really appreciate it if you would be kind enough to release codes for test or inference

Thank you very much

**Comment by PengleiGao** [comment]
Hi, we mainly focus on generalised outpainting. You could modify the codes for horizontal outpainting according to your own task.
I have uploaded the test file and you might have to change according to your own task.
