### ISSUE TITLE
from datasets.dataset import dataset_test4, dataset_arbi2, dataset_arbi3, 

### ISSUE THREAD

**Issue by JackTesla** [PengleiGao/UTransformer#3]
In the evaluate.py :
from datasets.dataset import dataset_test4, dataset_arbi2, dataset_arbi3, dataset_arbi

but there is no such package datasets,  there is only a dtaset.py ,  and in the dtaset.py there is no dataset_arbi2, dataset_arbi3, dataset_arbi.

Did you forget something in your code?

**Comment by PengleiGao** [comment]
Hi,
I have updated the dataset.py file.
You can import them now.

**Comment by JackTesla** [comment]
OK, thank you!
