### ISSUE TITLE
How to use the generator to generate images?

### ISSUE THREAD

**Issue by JackTesla** [PengleiGao/UTransformer#4]
Hello！ I have trained the model many iters. There is a problem. How to use the generator to generate images? I have tried the evaluate.py.But it seems no images generated.

**Comment by PengleiGao** [comment]
Hi，
the evaluate.py file could generate images normally.
You have to change the model name of your saved  xx.pth file in the red circle.
![image](https://user-images.githubusercontent.com/48986008/197494702-3e1be8d9-4006-4149-abff-598e1f53eb19.png)
