### ISSUE TITLE
 test or inference codes

### ISSUE THREAD

**Issue by zrymsm** [PengleiGao/UTransformer#5]
Hello, I'm very interested in this work of yours, but I can't seem to find the code for test or inference, could you provide a copy please?

**Comment by zrymsm** [comment]
And can you provide the code for the evaluation metric in question? I would be grateful!

**Comment by PengleiGao** [comment]
> Hello, I'm very interested in this work of yours, but I can't seem to find the code for test or inference, could you provide a copy please?

Hello, the file 'evaluate.py' is the code for inference. For evaluation metric, you can run 'cmd.py' to get the results. I have added this file.
Thanks.

**Comment by zrymsm** [comment]
Thx so much :)
